version: "3"
services:
  webapp:
    build: ./webapp
    environment:
      - VITE_REST_API_BASE_URL=http://localhost:8080
    ports:
      - 5173:5173
    depends_on:
      - api
    networks:
      - celsia-prueba-net
  api:
    build: ./api
    ports:
      - 8080:8080
    networks:
      - celsia-prueba-net
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USERNAME: 'user'
      DB_PASSWORD: '1234'
      FRONTEND_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    networks:
      - celsia-prueba-net
    environment:
      MYSQL_DATABASE: 'celsia-prueba-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
networks:
  celsia-prueba-net: